### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [tinahbu/dingpy#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.15. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary dingpy -w /tmp/ext dingpy==0.0.15
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting dingpy==0.0.15
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/980/220a5d79a202d/dingpy-0.0.15.tar.gz (5.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-bf25p2u_/dingpy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-bf25p2u_/dingpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-bf25p2u_/dingpy/pip-egg-info
         cwd: /tmp/pip-wheel-bf25p2u_/dingpy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-bf25p2u_/dingpy/setup.py", line 16, in <module>
        with open('HISTORY.md', 'r') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
I saw your comment in the PR, indeed this looks fixed.  Thanks!
